apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-cloud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-cloud-app
  template:
    metadata:
      labels:
        app: multi-cloud-app
    spec:
      containers:
      - name: multi-cloud-app
        image: us.icr.io/<namespace>/multi-cloud-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_APP
          value: "app.py"